"use client";

import { FormEvent, useEffect, useState } from "react";
import { Edit2, Plus, Trash2, X } from "lucide-react";

type Item = { id: number; title: string; description: string; attachment_url: string | null; published_at: string };
const empty = { title: "", description: "", attachment_url: "", published_at: "" };

export default function UrgentInformationAdminPage() {
  const [items, setItems] = useState<Item[]>([]); const [loading, setLoading] = useState(true); const [editing, setEditing] = useState<Item | null>(null); const [open, setOpen] = useState(false); const [form, setForm] = useState(empty); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); try { const response = await fetch("/api/urgent-information?limit=100"); const json = await response.json(); setItems(json.data || []); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const showCreate = () => { setEditing(null); setForm(empty); setOpen(true); };
  const showEdit = (item: Item) => { setEditing(item); setForm({ title: item.title, description: item.description, attachment_url: item.attachment_url || "", published_at: new Date(item.published_at).toISOString().slice(0, 16) }); setOpen(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const body = new FormData(); Object.entries(form).forEach(([key, value]) => body.append(key, value)); if (editing) body.append("id", String(editing.id)); const response = await fetch("/api/admin/urgent-information", { method: editing ? "PUT" : "POST", body }); if (!response.ok) throw new Error(); setOpen(false); await load(); } catch { alert("Gagal menyimpan informasi."); } finally { setSaving(false); } };
  const remove = async (id: number) => { if (!confirm("Hapus informasi ini?")) return; const response = await fetch("/api/admin/urgent-information", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); if (!response.ok) return alert("Gagal menghapus informasi."); await load(); };
  return <div className="space-y-6"><div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-2xl font-bold text-gray-900 sm:text-3xl">Informasi Serta Merta</h2><p className="mt-1 text-sm text-gray-500">Kelola pengumuman penting yang harus disampaikan segera kepada publik.</p></div><button onClick={showCreate} className="inline-flex items-center rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-700"><Plus className="mr-2 h-4 w-4" />Tambah Informasi</button></div>
    <div className="overflow-hidden rounded-lg border border-gray-200 bg-white shadow"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr><th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Judul & Deskripsi</th><th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Tanggal Publikasi</th><th className="px-6 py-3" /></tr></thead><tbody className="divide-y divide-gray-200">{loading ? <tr><td colSpan={3} className="px-6 py-8 text-center text-sm text-gray-500">Memuat data...</td></tr> : !items.length ? <tr><td colSpan={3} className="px-6 py-8 text-center text-sm text-gray-500">Belum ada informasi serta merta.</td></tr> : items.map((item) => <tr key={item.id}><td className="max-w-xl px-6 py-4"><p className="font-medium text-gray-900">{item.title}</p><p className="mt-1 line-clamp-2 text-sm text-gray-500">{item.description}</p></td><td className="whitespace-nowrap px-6 py-4 text-sm text-gray-500">{new Date(item.published_at).toLocaleDateString("id-ID")}</td><td className="whitespace-nowrap px-6 py-4 text-right"><button onClick={() => showEdit(item)} className="mr-3 text-blue-600 hover:text-blue-900"><Edit2 className="h-5 w-5" /></button><button onClick={() => void remove(item.id)} className="text-red-600 hover:text-red-900"><Trash2 className="h-5 w-5" /></button></td></tr>)}</tbody></table></div>
    {open && <div className="fixed inset-0 z-50 overflow-y-auto"><div className="flex min-h-screen items-center justify-center p-4"><button aria-label="Tutup" onClick={() => setOpen(false)} className="fixed inset-0 bg-slate-900/60" /><div className="relative w-full max-w-2xl rounded-xl bg-white shadow-xl"><form onSubmit={submit} className="p-6"><div className="mb-5 flex items-center justify-between"><h3 className="text-lg font-semibold">{editing ? "Edit Informasi" : "Tambah Informasi"}</h3><button type="button" onClick={() => setOpen(false)}><X className="h-6 w-6 text-gray-400" /></button></div><div className="space-y-4"><label className="block text-sm font-medium">Judul<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className="mt-1 w-full rounded-md border border-gray-300 px-3 py-2" /></label><label className="block text-sm font-medium">Deskripsi<textarea required rows={6} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="mt-1 w-full rounded-md border border-gray-300 px-3 py-2" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Tautan lampiran (opsional)<input type="url" value={form.attachment_url} onChange={(e) => setForm({ ...form, attachment_url: e.target.value })} className="mt-1 w-full rounded-md border border-gray-300 px-3 py-2" /></label><label className="block text-sm font-medium">Tanggal publikasi<input type="datetime-local" value={form.published_at} onChange={(e) => setForm({ ...form, published_at: e.target.value })} className="mt-1 w-full rounded-md border border-gray-300 px-3 py-2" /></label></div></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setOpen(false)} className="rounded-md border border-gray-300 px-4 py-2 text-sm">Batal</button><button disabled={saving} className="rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{saving ? "Menyimpan..." : "Simpan"}</button></div></form></div></div></div>}
  </div>;
}
