CREATE TABLE `passenger_stats` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `arrival_count` int(11) NOT NULL DEFAULT 0,
  `departure_count` int(11) NOT NULL DEFAULT 0,
  `category` varchar(20) NOT NULL DEFAULT 'domestic',
  `airline` varchar(100) DEFAULT NULL,
  `flight_type` varchar(20) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `passenger_count` int(11) DEFAULT 0,
  `load_factor` decimal(8,2) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `pax_adult` int(11) NOT NULL DEFAULT 0 COMMENT 'Dewasa (dihitung penumpang)',
  `pax_child` int(11) NOT NULL DEFAULT 0 COMMENT 'Anak (dihitung penumpang)',
  `pax_infant` int(11) NOT NULL DEFAULT 0 COMMENT 'Bayi (TIDAK dihitung, tetap tampil di PDF)',
  `pax_transit_adult` int(11) NOT NULL DEFAULT 0 COMMENT 'Transit dewasa',
  `pax_transit_child` int(11) NOT NULL DEFAULT 0 COMMENT 'Transit anak',
  `pax_transit_infant` int(11) NOT NULL DEFAULT 0 COMMENT 'Transit bayi',
  `baggage_kg` int(11) NOT NULL DEFAULT 0 COMMENT 'Bagasi (kg)',
  `cargo_kg` int(11) NOT NULL DEFAULT 0 COMMENT 'Kargo (kg)',
  `mail_kg` int(11) NOT NULL DEFAULT 0 COMMENT 'Pos (kg)',
  `flight_no` varchar(50) DEFAULT NULL,
  `origin` varchar(50) DEFAULT NULL,
  `destination` varchar(50) DEFAULT NULL,
  `type` varchar(50) DEFAULT NULL,
  `scheduled_time` varchar(50) DEFAULT NULL,
  `estimated_time` varchar(50) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `status_label` varchar(50) DEFAULT NULL,
  `notes` varchar(50) DEFAULT NULL,
  `flight_date` varchar(50) DEFAULT NULL,
  `updated_at` varchar(50) DEFAULT NULL,
  `seat_capacity` int(11) DEFAULT NULL,
  `aircraft_type` varchar(50) DEFAULT NULL,
  `is_scheduled` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
