name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH password
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd "${{ secrets.APP_DIR }}"

            git fetch origin master
            git reset --hard origin/master

            npm ci
            npm run build

            cp -r public .next/standalone/public
            mkdir -p .next/standalone/.next
            cp -r .next/static .next/standalone/.next/static

            TARGET_BASE="$(dirname "$PWD")/.next"

            mkdir -p "$TARGET_BASE"
            rm -rf "$TARGET_BASE/standalone"
            mv .next/standalone "$TARGET_BASE/standalone"